version: 2

jobs:
  macos:
    macos:
      xcode: "9.3"
    steps:
      - checkout
      - run: swift build
      - run: swift test
  linux:
    docker:
      - image: norionomura/swift:swift-4.1-branch
    steps:
      - run: apt-get install -y libssl-dev
      - checkout
      - run: swift build
      - run: swift test
workflows:
  version: 2
  tests:
    jobs:
      - linux
      - macos
